#############################################################################
# Makefile for building: Ledger
# Generated by qmake (3.1) (Qt 6.5.3)
# Project:  Ledger.pro
# Template: app
# Command: I:\OtherAPP\QTAPP\6.5.3\mingw_64\bin\qmake.exe -o Makefile Ledger.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

first: release
install: release-install
uninstall: release-uninstall
QMAKE         = I:\OtherAPP\QTAPP\6.5.3\mingw_64\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
QINSTALL      = I:\OtherAPP\QTAPP\6.5.3\mingw_64\bin\qmake.exe -install qinstall
QINSTALL_PROGRAM = I:\OtherAPP\QTAPP\6.5.3\mingw_64\bin\qmake.exe -install qinstall -exe
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
IDC           = idc
IDL           = midl
ZIP           = zip -r -9
DEF_FILE      = 
RES_FILE      = 
SED           = $(QMAKE) -install sed
MOVE          = move
SUBTARGETS    =  \
		release \
		debug


release: FORCE
	$(MAKE) -f $(MAKEFILE).Release
release-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Release 
release-all: FORCE
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: FORCE
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Release uninstall
debug: FORCE
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Debug 
debug-all: FORCE
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: FORCE
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Debug uninstall

Makefile: Ledger.pro I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/win32-g++/qmake.conf I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/features/spec_pre.prf \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/features/device_config.prf \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/common/sanitize.conf \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/common/gcc-base.conf \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/common/g++-base.conf \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/features/win32/windows_vulkan_sdk.prf \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/common/windows-vulkan.conf \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/common/g++-win32.conf \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/common/windows-desktop.conf \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/qconfig.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_ext_freetype.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_ext_libjpeg.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_ext_libpng.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_charts.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_charts_private.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_chartsqml.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_chartsqml_private.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_concurrent.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_core.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_core5compat.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_core5compat_private.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_core_private.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_dbus.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_dbus_private.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_designer.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_designer_private.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_entrypoint_private.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_example_icons_private.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_freetype_private.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_gui.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_gui_private.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_harfbuzz_private.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_help.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_help_private.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_jpeg_private.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_labsanimation.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_labsanimation_private.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_labssettings.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_labssettings_private.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_labssharedimage.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_linguist.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_linguist_private.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_mqtt.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_mqtt_private.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_network.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_network_private.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_opengl.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_opengl_private.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_openglwidgets.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_png_private.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_printsupport.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_qml.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_qml_private.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_qmlcore.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_qmlcore_private.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_qmldom_private.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_qmlintegration.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_qmlintegration_private.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_qmlmodels.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_qmltest.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_quick.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_quick_private.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_quickdialogs2.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_quickeffects_private.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_quicklayouts.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_quicktimeline.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_quicktimeline_private.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_serialbus.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_serialport.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_serialport_private.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_shadertools.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_shadertools_private.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_sql.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_sql_private.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_svg.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_svg_private.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_svgwidgets.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_testlib.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_testlib_private.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_tools_private.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_uiplugin.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_uitools.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_uitools_private.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_widgets.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_widgets_private.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_xml.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_xml_private.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_zlib_private.pri \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/features/qt_functions.prf \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/features/qt_config.prf \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/win32-g++/qmake.conf \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/features/exclusive_builds.prf \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/features/toolchain.prf \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/features/default_pre.prf \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/features/win32/default_pre.prf \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/features/resolve_config.prf \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/features/exclusive_builds_post.prf \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/features/default_post.prf \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/features/entrypoint.prf \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/features/precompile_header.prf \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/features/warn_on.prf \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/features/qt.prf \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/features/resources_functions.prf \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/features/resources.prf \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/features/moc.prf \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/features/win32/opengl.prf \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/features/uic.prf \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/features/qmake_use.prf \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/features/file_copies.prf \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/features/win32/windows.prf \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/features/testcase_targets.prf \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/features/exceptions.prf \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/features/yacc.prf \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/features/lex.prf \
		Ledger.pro \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/lib/Qt6Charts.prl \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/lib/Qt6OpenGLWidgets.prl \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/lib/Qt6Widgets.prl \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/lib/Qt6OpenGL.prl \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/lib/Qt6Gui.prl \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/lib/Qt6Core.prl \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/lib/Qt6EntryPoint.prl \
		I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/features/build_pass.prf
	$(QMAKE) -o Makefile Ledger.pro
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/features/spec_pre.prf:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/features/device_config.prf:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/common/sanitize.conf:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/common/gcc-base.conf:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/common/g++-base.conf:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/features/win32/windows_vulkan_sdk.prf:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/common/windows-vulkan.conf:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/common/g++-win32.conf:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/common/windows-desktop.conf:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/qconfig.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_ext_freetype.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_ext_libjpeg.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_ext_libpng.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_charts.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_charts_private.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_chartsqml.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_chartsqml_private.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_concurrent.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_concurrent_private.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_core.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_core5compat.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_core5compat_private.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_core_private.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_dbus.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_dbus_private.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_designer.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_designer_private.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_entrypoint_private.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_example_icons_private.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_fb_support_private.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_freetype_private.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_gui.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_gui_private.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_harfbuzz_private.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_help.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_help_private.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_jpeg_private.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_labsanimation.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_labsanimation_private.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_labsfolderlistmodel.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_labsqmlmodels.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_labsqmlmodels_private.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_labssettings.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_labssettings_private.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_labssharedimage.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_labssharedimage_private.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_labswavefrontmesh.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_linguist.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_linguist_private.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_mqtt.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_mqtt_private.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_network.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_network_private.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_opengl.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_opengl_private.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_openglwidgets.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_openglwidgets_private.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_png_private.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_printsupport.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_printsupport_private.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_qml.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_qml_private.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_qmlcompiler_private.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_qmlcore.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_qmlcore_private.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_qmldom_private.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_qmlintegration.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_qmlintegration_private.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_qmllocalstorage.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_qmllocalstorage_private.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_qmlmodels.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_qmlmodels_private.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_qmltest.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_qmltest_private.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_qmlworkerscript.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_qmlxmllistmodel.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_quick.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_quick_private.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_quickcontrols2impl.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_quickdialogs2.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_quickdialogs2_private.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_quickdialogs2utils.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_quickeffects_private.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_quicklayouts.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_quicklayouts_private.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_quickshapes_private.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_quicktemplates2.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_quicktimeline.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_quicktimeline_private.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_quickwidgets.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_serialbus.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_serialbus_private.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_serialport.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_serialport_private.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_shadertools.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_shadertools_private.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_sql.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_sql_private.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_svg.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_svg_private.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_svgwidgets.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_svgwidgets_private.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_testlib.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_testlib_private.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_tools_private.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_uiplugin.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_uitools.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_uitools_private.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_widgets.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_widgets_private.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_xml.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_xml_private.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/modules/qt_lib_zlib_private.pri:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/features/qt_functions.prf:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/features/qt_config.prf:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/win32-g++/qmake.conf:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/features/spec_post.prf:
.qmake.stash:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/features/exclusive_builds.prf:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/features/toolchain.prf:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/features/default_pre.prf:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/features/win32/default_pre.prf:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/features/resolve_config.prf:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/features/exclusive_builds_post.prf:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/features/default_post.prf:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/features/entrypoint.prf:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/features/precompile_header.prf:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/features/warn_on.prf:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/features/qt.prf:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/features/resources_functions.prf:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/features/resources.prf:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/features/moc.prf:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/features/win32/opengl.prf:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/features/uic.prf:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/features/qmake_use.prf:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/features/file_copies.prf:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/features/win32/windows.prf:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/features/testcase_targets.prf:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/features/exceptions.prf:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/features/yacc.prf:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/features/lex.prf:
Ledger.pro:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/lib/Qt6Charts.prl:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/lib/Qt6OpenGLWidgets.prl:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/lib/Qt6Widgets.prl:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/lib/Qt6OpenGL.prl:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/lib/Qt6Gui.prl:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/lib/Qt6Core.prl:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/lib/Qt6EntryPoint.prl:
I:/OtherAPP/QTAPP/6.5.3/mingw_64/mkspecs/features/build_pass.prf:
qmake: FORCE
	@$(QMAKE) -o Makefile Ledger.pro

qmake_all: FORCE

make_first: release-make_first debug-make_first  FORCE
all: release-all debug-all  FORCE
clean: release-clean debug-clean  FORCE
distclean: release-distclean debug-distclean  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) .qmake.stash

release-mocclean:
	$(MAKE) -f $(MAKEFILE).Release mocclean
debug-mocclean:
	$(MAKE) -f $(MAKEFILE).Debug mocclean
mocclean: release-mocclean debug-mocclean

release-mocables:
	$(MAKE) -f $(MAKEFILE).Release mocables
debug-mocables:
	$(MAKE) -f $(MAKEFILE).Debug mocables
mocables: release-mocables debug-mocables

check: first

benchmark: first
FORCE:

.SUFFIXES:

$(MAKEFILE).Release: Makefile
$(MAKEFILE).Debug: Makefile
